# -*- coding: utf-8 -*-
"""mediadoaluno.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d12hfHL9vF4GmrJlWQaJS4Ny3NnKvucs
"""



"""um aluno vai receber três notas de forma dinâmica, por entrada de dados , e se o aluno tirar entre 10 e 7 de média ele será aprovado,senão,se o aluno tirar menos do que 7 e mais do que 4 ele ainda vai para final, senão o aluno reprova automaticamente. A sáida de dados deve conter a média do aluno e a sua situação de acordo com a sua média.

"""

nota1 = float(input("informe sua primeira nota"))
nota2 = float(input("informe sua segunda nota"))
nota3 = float(input("informe sua terceira nota"))

media =(nota1+nota2+nota3) /3

if(media  >= 7 ):
    print("aprovado")

elif(media >= 4 ):
     print("reprovado")
else:
    media('para final')
print(f'situação do aluno {media}' )